**Basic Vector and Matrix Operation with Numpy.**

Problem - 1: Array Creation:

In [1]:
import numpy as np

# 1. Initialize an empty array with size 2X2.
empty_array = np.empty((2, 2))
print("Empty 2x2 array:\n", empty_array)

Empty 2x2 array:
 [[3.03112312e-316 0.00000000e+000]
 [4.22797985e-307 1.00813461e-109]]


In [2]:
# 2. Initialize an all one array with size 4X2.
ones_array = np.ones((4, 2))
print("All ones 4x2 array:\n", ones_array)

All ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [3]:
# 3. Return a new array of given shape and type, filled with fill value.
filled_array = np.full((3, 3), 5)  # Fill with value 5
print("Filled 3x3 array with value 5:\n", filled_array)

Filled 3x3 array with value 5:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]


In [4]:
# 4. Return a new array of zeros with same shape and type as a given array.
zeros_like_array = np.zeros_like(filled_array)
print("Zeros array with same shape as filled_array:\n", zeros_like_array)

Zeros array with same shape as filled_array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
# 5. Return a new array of ones with same shape and type as a given array.
ones_like_array = np.ones_like(filled_array)
print("Ones array with same shape as filled_array:\n", ones_like_array)

Ones array with same shape as filled_array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [6]:
# 6. Convert an existing list to a numpy array.
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Numpy array from list:\n", numpy_array)

Numpy array from list:
 [1 2 3 4]



**Problem - 2: Array Manipulation: Numerical Ranges and Array Indexing**

In [7]:
# 1. Create an array with values ranging from 10 to 49.
range_array = np.arange(10, 50)
print("Array with values from 10 to 49:\n", range_array)

Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
# 2. Create a 3X3 matrix with values ranging from 0 to 8.
reshaped_array = np.arange(9).reshape(3, 3)
print("3x3 matrix with values 0 to 8:\n", reshaped_array)

3x3 matrix with values 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
# 3. Create a 3X3 identity matrix.
identity_matrix = np.eye(3)
print("3x3 identity matrix:\n", identity_matrix)

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# 4. Create a random array of size 30 and find the mean of the array.
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random array of size 30:\n", random_array)
print("Mean of the array:", mean_value)

Random array of size 30:
 [0.21528164 0.12620344 0.78989901 0.83071603 0.34698374 0.40844746
 0.49724539 0.48070458 0.7958108  0.90172762 0.4598472  0.55293292
 0.24005193 0.74189364 0.96374782 0.71182139 0.99554369 0.52953687
 0.16332601 0.94923564 0.16841329 0.67606318 0.86952918 0.33118169
 0.68932009 0.52944754 0.33715684 0.70474888 0.07631258 0.45792818]
Mean of the array: 0.5513686084910306


In [11]:
# 5. Create a 10X10 array with random values and find the minimum and maximum values.
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("10x10 random array:\n", random_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

10x10 random array:
 [[0.51566443 0.92123463 0.58302924 0.41712168 0.8577741  0.25071976
  0.55310609 0.57621058 0.28006186 0.34197652]
 [0.00557827 0.67699869 0.92006416 0.38970743 0.36001054 0.31789997
  0.6733685  0.12548246 0.37029063 0.51112633]
 [0.46764594 0.73368769 0.23051841 0.64505091 0.20510504 0.43991243
  0.40288356 0.97457854 0.39294601 0.59724396]
 [0.5475046  0.49365614 0.65859645 0.51531845 0.8126717  0.04878171
  0.27485299 0.77303214 0.48958714 0.17181319]
 [0.3475228  0.07655658 0.24624909 0.12068869 0.5784777  0.94861314
  0.80063037 0.96233273 0.28370822 0.90682622]
 [0.78320355 0.69866699 0.65258963 0.1716916  0.29698508 0.82827566
  0.17947373 0.49850581 0.92468745 0.03836305]
 [0.37462212 0.01732358 0.36021101 0.30478706 0.94734223 0.88309409
  0.22599979 0.17574791 0.36501063 0.29327228]
 [0.54594508 0.42403751 0.60331209 0.00530445 0.78518362 0.09707631
  0.49873904 0.1043694  0.632068   0.31447433]
 [0.69753273 0.02286894 0.82706028 0.53846237 0.03268537 0.

In [12]:
# 6. Create a zero array of size 10 and replace the 5th element with 1.
zero_array = np.zeros(10)
zero_array[4] = 1  # Indexing starts from 0
print("Zero array with 5th element replaced by 1:\n", zero_array)

Zero array with 5th element replaced by 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0].
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed array:\n", reversed_arr)

Reversed array:
 [0 4 0 0 2 1]


In [14]:
# 8. Create a 2D array with 1 on the border and 0 inside.
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D array with 1 on border and 0 inside:\n", border_array)

2D array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
# 9. Create an 8X8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 checkerboard pattern:\n", checkerboard)

8x8 checkerboard pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**Problem - 3: Array Operations**

In [16]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays.
add_result = x + y
print("Addition of x and y:\n", add_result)

Addition of x and y:
 [[ 6  8]
 [10 13]]


In [17]:
# 2. Subtract the two arrays.
sub_result = x - y
print("Subtraction of x and y:\n", sub_result)

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]


In [18]:
# 3. Multiply the array with any integer.
mul_result = x * 2
print("Multiplication of x by 2:\n", mul_result)

Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]


In [19]:
# 4. Find the square of each element of the array.
square_result = x**2
print("Square of each element in x:\n", square_result)

Square of each element in x:
 [[ 1  4]
 [ 9 25]]


In [20]:
# 5. Find the dot product between: v and w; x and v; x and y.
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:", dot_xv)
print("Dot product of x and y:\n", dot_xy)

Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


In [21]:
# 6. Concatenate x and y along row and v and w along column.
concat_row = np.concatenate((x, y), axis=0)
concat_col = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)
print("Concatenation of x and y along row:\n", concat_row)
print("Concatenation of v and w along column:\n", concat_col)

Concatenation of x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along column:
 [[ 9 11]
 [10 12]]


In [22]:
# 7. Concatenate x and v; observe and explain the error.
try:
    concat_xv = np.concatenate((x, v))
except ValueError as e:
    print("Error:", e)
    print("Explanation: x and v have different shapes. x is 2x2 and v is 1D with shape (2,).")

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x and v have different shapes. x is 2x2 and v is 1D with shape (2,).


**Problem - 4: Matrix Operations**

In [23]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A−1 = I.
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print("A.A^{-1}:\n", identity_check)





A.A^{-1}:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [24]:
# 2. Prove AB ≠ BA.
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)
print("AB != BA:", not np.array_equal(AB, BA))

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB != BA: True


In [25]:
# 3. Prove (AB)^T = B^T A^T.
AB_T = AB.T
B_T_A_T = np.dot(B.T, A.T)
print("(AB)^T:\n", AB_T)
print("B^T A^T:\n", B_T_A_T)
print("(AB)^T == B^T A^T:", np.array_equal(AB_T, B_T_A_T))

# Solve the system of linear equations using the inverse method.
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])
X = np.linalg.inv(A_eq) @ B_eq
print("Solution to the system of equations:", X)

# Solve using np.linalg.inv
X_inv = np.linalg.solve(A_eq, B_eq)
print("Solution using np.linalg.solve:", X_inv)

(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
(AB)^T == B^T A^T: True
Solution to the system of equations: [ 2.  1. -2.]
Solution using np.linalg.solve: [ 2.  1. -2.]


**Problem - 5: Performance Comparison (Numpy vs Python Lists)**

In [26]:
import time

# Element-wise Addition
python_list1 = [i for i in range(1000000)]
python_list2 = [i for i in range(1000000)]
start_time = time.time()
result = [a + b for a, b in zip(python_list1, python_list2)]
print("Python list addition time:", time.time() - start_time)

numpy_array1 = np.arange(1000000)
numpy_array2 = np.arange(1000000)
start_time = time.time()
result = numpy_array1 + numpy_array2
print("Numpy array addition time:", time.time() - start_time)

Python list addition time: 0.05854630470275879
Numpy array addition time: 0.008169412612915039


In [27]:
# Element-wise Multiplication
start_time = time.time()
result = [a * b for a, b in zip(python_list1, python_list2)]
print("Python list multiplication time:", time.time() - start_time)

start_time = time.time()
result = numpy_array1 * numpy_array2
print("Numpy array multiplication time:", time.time() - start_time)

Python list multiplication time: 0.056739091873168945
Numpy array multiplication time: 0.008426427841186523


In [28]:
# Dot Product
start_time = time.time()
dot_product = sum(a * b for a, b in zip(python_list1, python_list2))
print("Python list dot product time:", time.time() - start_time)

start_time = time.time()
dot_product = np.dot(numpy_array1, numpy_array2)
print("Numpy array dot product time:", time.time() - start_time)

Python list dot product time: 0.08087372779846191
Numpy array dot product time: 0.0010726451873779297


In [29]:

# Matrix Multiplication
python_matrix1 = [[i + j for j in range(1000)] for i in range(1000)]
python_matrix2 = [[i + j for j in range(1000)] for i in range(1000)]
start_time = time.time()
result = [[sum(a * b for a, b in zip(row, col)) for col in zip(*python_matrix2)] for row in python_matrix1]
print("Python list matrix multiplication time:", time.time() - start_time)

numpy_matrix1 = np.random.random((1000, 1000))
numpy_matrix2 = np.random.random((1000, 1000))
start_time = time.time()
result = np.dot(numpy_matrix1, numpy_matrix2)
print("Numpy array matrix multiplication time:", time.time() - start_time)

Python list matrix multiplication time: 84.30873465538025
Numpy array matrix multiplication time: 0.0708012580871582
